# Generated by Django 4.1.1 on 2022-12-02 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppServicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
